# Kortti, note, pakka, tagi ???  

Kaikki nämä perusteet käydään käytännössä läpi osiossa 3. Tässä on vain yleiskuva siitä, mitä nämä ovat.

## Kortti 

Kysymys-vastaus-paria kutsutaan kortiksi (card). Se on hyvin samanlainen kuin fyysinen muistikortti eli paperi, jonka toisella puolella on kysymys ja toisella vastaus. 

- Se pohja, jonka tyylisiksi erilaiset kortit luodaan, on nimeltään note type. 

## Note -tyypit

Kts. aiheesta tarkemmin osiossa 6.

Ankissa voi luoda todella monta erityyppistä korttia. Tässä niistä tärkeimmät:

- Ankista natiivistikin löytyvä "Basic" on yksinkertainen kortti, jossa on vain kysymys ja vastaus. Voi myös luoda Basic (and reversed card), jolloin luodaan kaksi korttia kirjoitetusta teksistä: etu -> taka ja taka -> etu 
- "Cloze" on kortti, jossa on teksti, josta on poistettu joitakin sanoja. Kortin vastaus on piilotetut sanat. Tämä on yleisimmin käyttämäni korttityyppi ja Ranki pääasiassa sisältää vain näitä. 
- "Image occlusion" -notella pystyy piilottamaan osia kuvista; mahtava tapa opiskella esim. anatomiaa 

## Pakka (deck)

Pakka on korttien joukko. Eri pakkoihin voi koota eri aiheita käsitteleviä kortteja, jotta kaikkea ei tarvitse opiskella sekalaisesti. 

- Kaikilla pakoilla voi olla omat asetuksensa. 

Pakoissa voi olla alapakkoja, voit luoda niitä klikkaamalla "Create Deck" -painiketta. Jos emopakan nimi on Default, niin voit luoda sen alle alapakan kirjoittamalla emopakan nimen perään kaksi kaksoispistettä ja sitten uuden pakan nimen, esimerkiksi: "Default::Alapakka".

- Näin pystyt erottelemaan eri aihekokonaisuuksia saman pakan alla, jos haluat pitää kortit hyvin organisoituina. Toinen tapa organisoida kortteja on tagien avulla.

## Tagit 

Saman ja jopa eri pakkojen välillä kortteja voi luokitella tagien avulla. Esimerkiksi Ranki on jaoteltu pelkästään tagien avulla.

- Tagien hyöty verrattuna alapakkoihin on se, että yksi ja sama kortti voi olla useissa eri kokonaisuuksissa sen mukaan, mitä tageja siinä on. Etsimällä haluamansa tagin voi opiskella kyseisen tägin kortteja. 
- Taas alapakasta löytyvää tägitöntä korttia ei voi löytyä mistään muualta kuin vain siitä alapakasta, jossa se on. 